USE GENDER_STATS;

DROP TABLE IF EXISTS Q2;

CREATE TABLE Q2
AS SELECT TRANSFORM (*)
USING 'python hivetest.py' 
AS (COUNTRY, PERCENT) 
FROM GENDER
WHERE COUNTRY_CODE='USA' AND (INDICATOR_CODE='SE.TER.CMPL.FE.ZS' OR INDICATOR_CODE='SE.TER.CMPL.MA.ZS');