USE GENDER_STATS;

DROP TABLE IF EXISTS QUESTION_5;
DROP TABLE IF EXISTS QUESTION_5_OUTPUT;

CREATE TABLE QUESTION_5 AS
SELECT * FROM GENDER
WHERE INDICATOR_NAME='School enrollment, tertiary (gross), gender parity index (GPI)';

add file hdfs:///user/p2/scripts/q5/question5hive.py;

CREATE TABLE QUESTION_5_OUTPUT
AS SELECT TRANSFORM (*)
USING 'python question5hive.py'
AS (COUNTRY, INDICATION, EARLIEST_YEAR, LATEST_YEAR, DIFFERENCE)
FROM QUESTION_5;
